// SPDX-License-Identifier: GPL-2.0-only

#ifndef _DT_BINDINGS_SOC_BCM_KONA_PI_H
#define _DT_BINDINGS_SOC_BCM_KONA_PI_H

#define BCMKONA_POWER_DOMAIN_MM			0
#define BCMKONA_POWER_DOMAIN_HUB_SWITCHABLE	1
#define BCMKONA_POWER_DOMAIN_HUB_AON		2
#define BCMKONA_POWER_DOMAIN_ARM_CORE		3
#define BCMKONA_POWER_DOMAIN_ARM_SUBSYSTEM	4
#define BCMKONA_POWER_DOMAIN_MODEM		5

#define BCMKONA_POWER_DOMAIN_COUNT		6

#endif /* _DT_BINDINGS_SOC_BCM_KONA_PI_H */

